#!/bin/sh

if [ -z "$1" ] ; then
  echo "Repository name is required."
  exit 1
fi

if [ -z "$2" ] ; then
  echo "New branch name is required."
  exit 1
fi

if [ ! $(git check-ref-format --normalize "refs/heads/$2") ] ; then
  echo "Invalid branch name."
  exit 1
fi

if (echo $1 | egrep -q '\.git$') ; then
  NAME=$1
else
  NAME=$1.git
fi

cd $NAME
git symbolic-ref HEAD refs/heads/$2
echo "$NAME default branch is now $2"
