#!/bin/sh

echo "Commands:"
echo "  default-branch REPONAME BRANCH  Change the default branch of a repo"
echo "  create REPONAME                 Create a bare repository"
echo "  delete REPONAME                 Delete a repository"
echo "  list                            List repositories"
echo "  help                            Display this help"
echo "  exit                            Disconnect from git-shell"
